version: '3.1'

volumes:
    uploads: {}
    db: {}
    static: {}
    src: {}

services:
    mongo:
        image: mongo
        expose:
            - "27017"
        restart: unless-stopped
        volumes:
            - db:/data/db

    mongo-express:
        image: mongo-express
        restart: unless-stopped
        depends_on:
            - mongo
        ports:
            - "8081:8081"

    sync:
        build: src/docker/sync
        restart: unless-stopped
        volumes:
            - ./src:/dev/src/:consistent
            - ./static:/dev/static/:ro
            - src:/app/src
            - static:/app/static

    server:
        build:
            context: .
            dockerfile: src/docker/dev/Dockerfile
        restart: unless-stopped
        depends_on:
            - 'mongo'
        ports:
            - "3000:3000"
            - "24678:24678"
        volumes:
            - src:/app/src
            - static:/app/static